name: learn-github-actions
on:
  push:
    branches:
      - main

jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2 #plugin for setting up the java
        with:
          distribution: "zulu"
          java-version: "11" #defines the java version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.5" #You can define the flutter version.
      - run: flutter pub get #installing the plugins for the flutter project
      - run: flutter test #running flutter test
      - run: flutter build apk #building flutter apk
      - name: Create github artifact release # disable this to save storage
        - uses: actions/upload-artifact@v1
          with:
            name: release-apk
            path: build/app/outputs/apk/release/app-release.apk

  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: release-apk
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          group: testers
          file: app-release.apk