name: learn-github-actions
on:
  push:
    branches:
      - main

jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2 #plugin for setting up the java
        with:
          distribution: "zulu"
          java-version: "11" #defines the java version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.5" #You can define the flutter version.
      - run: flutter pub get #installing the plugins for the flutter project
      - run: flutter test #running flutter test
      - run: flutter build apk #building flutter apk
